### ISSUE TITLE
Comment Box element are going over footer title

### ISSUE THREAD

**Issue by c-rom** [felixdorner/yuuta#3]
![capture d ecran 2016-01-07 a 21 10 08](https://cloud.githubusercontent.com/assets/546838/12181733/4c49095e-b584-11e5-85db-0a321cfef98f.png)

Quick fix : 

``` css
.comment-subscription-form { display: none; }
.respond-active .comment-subscription-form { color: #989898; display: block; text-align: left; margin-left: 20px; }
```
